### ISSUE TITLE
App not building or starting

### ISSUE THREAD

**Issue by zannain** [vbosquet/jamming#1]
Hello, 

I tried to build your project but I'm getting the following error:

```
Module not found: You attempted to import /Users/virginie/sites/jamming/src/util/Spotify which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/.
```

Is there a missing file you have not committed yet to Git?

**Comment by vbosquet** [comment]
I resolved the problem (which was a incorrect path). Normally, you would be able to build the project.
